# Variables for nginx role
---
NGINX_HTPASSWD_USER: jarv
NGINX_HTPASSWD_PASS: radiogaga
NGINX_ENABLE_BASIC_AUTH: true
NGINX_ENABLE_SSL: False
# Set these to real paths on your
# filesystem, otherwise nginx will
# use a self-signed snake-oil cert
#
# To use a certificate chain add the contents
# to your certificate:
#
# cat www.example.com.crt bundle.crt > www.example.com.chained.crt

NGINX_SSL_CERTIFICATE: 'ssl-cert-snakeoil.pem'
NGINX_SSL_KEY: 'ssl-cert-snakeoil.key'

# When set to False, nginx will pass X-Forwarded-For, X-Forwarded-Port,
# and X-Forwarded-Proto headers through to the backend unmodified.
# This is desired when nginx is deployed behind another load balancer
# which takes care of properly setting the X-Forwarded-* headers.
# When there is no other load balancer in front of nginx, set this
# variable to True to force nginx to set the values of the X-Forwarded-*
# headers to reflect the properties of the incoming request.
NGINX_SET_X_FORWARDED_HEADERS: False

nginx_app_dir: "/etc/nginx"
nginx_data_dir: "/etc/nginx"
nginx_conf_dir: "/etc/nginx//conf.d"
nginx_log_dir: "/var/log/nginx"
nginx_sites_available_dir: "{{ nginx_app_dir }}/sites-available"
nginx_sites_enabled_dir: "{{ nginx_app_dir }}/sites-enabled"
nginx_user: root
nginx_htpasswd_file: "{{ nginx_app_dir }}/nginx.htpasswd"
nginx_default_sites: []
nginx_debian_pkgs:
  - nginx
  - python-passlib

NGINX_ROBOT_RULES: [ ]
nginx_sites: []
